export default {
  CREATE_ONE_TASK: 'CREATE_ONE_TASK',
  READ_ALL_TASKS: 'READ_ALL_TASKS',
  UPDATE_TASK_BY_ID: 'DELETE_TASK_BY_ID',
  DELETE_TASK_BY_ID: 'DELETE_TASK_BY_ID',

  GET_TASK_BY_ID: 'GET_TASK_BY_ID',
};
