/* eslint-disable  */

const data = {
  data: {
    request: [
      {
        type: 'City',
        query: 'Kiev, Ukraine',
      },
    ],
    current_condition: [
      {
        observation_time: '02:45 PM',
        localObsDateTime: '2020-03-27 04:45 PM',
        temp_C: '16',
        temp_F: '61',
        weatherCode: '113',
        weatherIconUrl: [
          {
            value:
              'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0001_sunny.png',
          },
        ],
        weatherDesc: [
          {
            value: 'Sunny',
          },
        ],
        lang_uk: [
          {
            value: 'Сонячно',
          },
        ],
        windspeedMiles: '9',
        windspeedKmph: '15',
        winddirDegree: '80',
        winddir16Point: 'E',
        precipMM: '0.0',
        precipInches: '0.0',
        humidity: '13',
        visibility: '10',
        visibilityMiles: '6',
        pressure: '1025',
        pressureInches: '31',
        cloudcover: '0',
        FeelsLikeC: '16',
        FeelsLikeF: '61',
        uvIndex: 3,
      },
    ],
    weather: [
      {
        date: '2020-03-27',
        astronomy: [
          {
            sunrise: '05:45 AM',
            sunset: '06:23 PM',
            moonrise: '07:16 AM',
            moonset: '09:32 PM',
            moon_phase: 'Waxing Crescent',
            moon_illumination: '18',
          },
        ],
        maxtempC: '13',
        maxtempF: '55',
        mintempC: '3',
        mintempF: '38',
        avgtempC: '8',
        avgtempF: '47',
        totalSnow_cm: '0.0',
        sunHour: '12.8',
        uvIndex: '3',
        hourly: [
          {
            time: '0',
            tempC: '5',
            tempF: '42',
            windspeedMiles: '7',
            windspeedKmph: '11',
            winddirDegree: '66',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '58',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1032',
            pressureInches: '31',
            cloudcover: '7',
            HeatIndexC: '5',
            HeatIndexF: '42',
            DewPointC: '-2',
            DewPointF: '28',
            WindChillC: '3',
            WindChillF: '37',
            WindGustMiles: '11',
            WindGustKmph: '18',
            FeelsLikeC: '3',
            FeelsLikeF: '37',
            chanceofrain: '0',
            chanceofremdry: '94',
            chanceofwindy: '0',
            chanceofovercast: '44',
            chanceofsunshine: '79',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '100',
            tempC: '5',
            tempF: '40',
            windspeedMiles: '7',
            windspeedKmph: '11',
            winddirDegree: '66',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '60',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1032',
            pressureInches: '31',
            cloudcover: '10',
            HeatIndexC: '5',
            HeatIndexF: '40',
            DewPointC: '-2',
            DewPointF: '28',
            WindChillC: '2',
            WindChillF: '36',
            WindGustMiles: '11',
            WindGustKmph: '18',
            FeelsLikeC: '2',
            FeelsLikeF: '36',
            chanceofrain: '0',
            chanceofremdry: '93',
            chanceofwindy: '0',
            chanceofovercast: '45',
            chanceofsunshine: '79',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '200',
            tempC: '4',
            tempF: '40',
            windspeedMiles: '7',
            windspeedKmph: '11',
            winddirDegree: '65',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '61',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1032',
            pressureInches: '31',
            cloudcover: '13',
            HeatIndexC: '4',
            HeatIndexF: '40',
            DewPointC: '-3',
            DewPointF: '27',
            WindChillC: '2',
            WindChillF: '35',
            WindGustMiles: '11',
            WindGustKmph: '18',
            FeelsLikeC: '2',
            FeelsLikeF: '35',
            chanceofrain: '0',
            chanceofremdry: '93',
            chanceofwindy: '0',
            chanceofovercast: '47',
            chanceofsunshine: '79',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '300',
            tempC: '4',
            tempF: '39',
            windspeedMiles: '7',
            windspeedKmph: '11',
            winddirDegree: '64',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '63',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1031',
            pressureInches: '31',
            cloudcover: '12',
            HeatIndexC: '4',
            HeatIndexF: '39',
            DewPointC: '-3',
            DewPointF: '28',
            WindChillC: '1',
            WindChillF: '34',
            WindGustMiles: '11',
            WindGustKmph: '18',
            FeelsLikeC: '1',
            FeelsLikeF: '34',
            chanceofrain: '0',
            chanceofremdry: '93',
            chanceofwindy: '0',
            chanceofovercast: '45',
            chanceofsunshine: '79',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '400',
            tempC: '4',
            tempF: '39',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '63',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '64',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1031',
            pressureInches: '31',
            cloudcover: '11',
            HeatIndexC: '4',
            HeatIndexF: '39',
            DewPointC: '-2',
            DewPointF: '28',
            WindChillC: '1',
            WindChillF: '34',
            WindGustMiles: '11',
            WindGustKmph: '18',
            FeelsLikeC: '1',
            FeelsLikeF: '34',
            chanceofrain: '0',
            chanceofremdry: '93',
            chanceofwindy: '0',
            chanceofovercast: '44',
            chanceofsunshine: '78',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '500',
            tempC: '3',
            tempF: '38',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '62',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '66',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1031',
            pressureInches: '31',
            cloudcover: '10',
            HeatIndexC: '3',
            HeatIndexF: '38',
            DewPointC: '-2',
            DewPointF: '28',
            WindChillC: '1',
            WindChillF: '33',
            WindGustMiles: '11',
            WindGustKmph: '17',
            FeelsLikeC: '1',
            FeelsLikeF: '33',
            chanceofrain: '0',
            chanceofremdry: '93',
            chanceofwindy: '0',
            chanceofovercast: '42',
            chanceofsunshine: '78',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '600',
            tempC: '4',
            tempF: '39',
            windspeedMiles: '7',
            windspeedKmph: '11',
            winddirDegree: '63',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '63',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1031',
            pressureInches: '31',
            cloudcover: '16',
            HeatIndexC: '4',
            HeatIndexF: '39',
            DewPointC: '-2',
            DewPointF: '28',
            WindChillC: '1',
            WindChillF: '34',
            WindGustMiles: '11',
            WindGustKmph: '17',
            FeelsLikeC: '1',
            FeelsLikeF: '34',
            chanceofrain: '0',
            chanceofremdry: '89',
            chanceofwindy: '0',
            chanceofovercast: '44',
            chanceofsunshine: '79',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '700',
            tempC: '5',
            tempF: '40',
            windspeedMiles: '8',
            windspeedKmph: '12',
            winddirDegree: '65',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '60',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1030',
            pressureInches: '31',
            cloudcover: '21',
            HeatIndexC: '5',
            HeatIndexF: '40',
            DewPointC: '-3',
            DewPointF: '28',
            WindChillC: '2',
            WindChillF: '35',
            WindGustMiles: '10',
            WindGustKmph: '17',
            FeelsLikeC: '2',
            FeelsLikeF: '35',
            chanceofrain: '0',
            chanceofremdry: '84',
            chanceofwindy: '0',
            chanceofovercast: '45',
            chanceofsunshine: '80',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '800',
            tempC: '5',
            tempF: '41',
            windspeedMiles: '8',
            windspeedKmph: '13',
            winddirDegree: '67',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '58',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1030',
            pressureInches: '31',
            cloudcover: '26',
            HeatIndexC: '5',
            HeatIndexF: '41',
            DewPointC: '-3',
            DewPointF: '27',
            WindChillC: '2',
            WindChillF: '36',
            WindGustMiles: '10',
            WindGustKmph: '16',
            FeelsLikeC: '2',
            FeelsLikeF: '36',
            chanceofrain: '0',
            chanceofremdry: '80',
            chanceofwindy: '0',
            chanceofovercast: '47',
            chanceofsunshine: '81',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '900',
            tempC: '7',
            tempF: '44',
            windspeedMiles: '8',
            windspeedKmph: '13',
            winddirDegree: '66',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '52',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1030',
            pressureInches: '31',
            cloudcover: '24',
            HeatIndexC: '7',
            HeatIndexF: '44',
            DewPointC: '-3',
            DewPointF: '27',
            WindChillC: '4',
            WindChillF: '40',
            WindGustMiles: '10',
            WindGustKmph: '16',
            FeelsLikeC: '4',
            FeelsLikeF: '40',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '44',
            chanceofsunshine: '82',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1000',
            tempC: '9',
            tempF: '47',
            windspeedMiles: '8',
            windspeedKmph: '13',
            winddirDegree: '66',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '46',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1029',
            pressureInches: '31',
            cloudcover: '21',
            HeatIndexC: '9',
            HeatIndexF: '47',
            DewPointC: '-3',
            DewPointF: '28',
            WindChillC: '6',
            WindChillF: '44',
            WindGustMiles: '10',
            WindGustKmph: '16',
            FeelsLikeC: '6',
            FeelsLikeF: '44',
            chanceofrain: '0',
            chanceofremdry: '89',
            chanceofwindy: '0',
            chanceofovercast: '41',
            chanceofsunshine: '84',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1100',
            tempC: '10',
            tempF: '51',
            windspeedMiles: '8',
            windspeedKmph: '13',
            winddirDegree: '66',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '41',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1029',
            pressureInches: '31',
            cloudcover: '18',
            HeatIndexC: '10',
            HeatIndexF: '51',
            DewPointC: '-3',
            DewPointF: '28',
            WindChillC: '9',
            WindChillF: '47',
            WindGustMiles: '10',
            WindGustKmph: '15',
            FeelsLikeC: '9',
            FeelsLikeF: '47',
            chanceofrain: '0',
            chanceofremdry: '94',
            chanceofwindy: '0',
            chanceofovercast: '38',
            chanceofsunshine: '85',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1200',
            tempC: '11',
            tempF: '52',
            windspeedMiles: '9',
            windspeedKmph: '14',
            winddirDegree: '65',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '38',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1028',
            pressureInches: '31',
            cloudcover: '28',
            HeatIndexC: '11',
            HeatIndexF: '52',
            DewPointC: '-3',
            DewPointF: '27',
            WindChillC: '10',
            WindChillF: '49',
            WindGustMiles: '10',
            WindGustKmph: '17',
            FeelsLikeC: '10',
            FeelsLikeF: '49',
            chanceofrain: '0',
            chanceofremdry: '89',
            chanceofwindy: '0',
            chanceofovercast: '41',
            chanceofsunshine: '80',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1300',
            tempC: '12',
            tempF: '54',
            windspeedMiles: '9',
            windspeedKmph: '15',
            winddirDegree: '65',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '36',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1028',
            pressureInches: '31',
            cloudcover: '38',
            HeatIndexC: '12',
            HeatIndexF: '54',
            DewPointC: '-3',
            DewPointF: '27',
            WindChillC: '10',
            WindChillF: '51',
            WindGustMiles: '11',
            WindGustKmph: '18',
            FeelsLikeC: '10',
            FeelsLikeF: '51',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '45',
            chanceofsunshine: '76',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1400',
            tempC: '13',
            tempF: '55',
            windspeedMiles: '10',
            windspeedKmph: '16',
            winddirDegree: '64',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '33',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1027',
            pressureInches: '31',
            cloudcover: '48',
            HeatIndexC: '13',
            HeatIndexF: '55',
            DewPointC: '-3',
            DewPointF: '27',
            WindChillC: '11',
            WindChillF: '53',
            WindGustMiles: '12',
            WindGustKmph: '19',
            FeelsLikeC: '11',
            FeelsLikeF: '53',
            chanceofrain: '0',
            chanceofremdry: '80',
            chanceofwindy: '0',
            chanceofovercast: '48',
            chanceofsunshine: '71',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1500',
            tempC: '13',
            tempF: '55',
            windspeedMiles: '9',
            windspeedKmph: '15',
            winddirDegree: '65',
            winddir16Point: 'ENE',
            weatherCode: '119',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Хмарно',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '35',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1026',
            pressureInches: '31',
            cloudcover: '56',
            HeatIndexC: '13',
            HeatIndexF: '55',
            DewPointC: '-2',
            DewPointF: '28',
            WindChillC: '11',
            WindChillF: '52',
            WindGustMiles: '12',
            WindGustKmph: '19',
            FeelsLikeC: '11',
            FeelsLikeF: '52',
            chanceofrain: '0',
            chanceofremdry: '84',
            chanceofwindy: '0',
            chanceofovercast: '60',
            chanceofsunshine: '53',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1600',
            tempC: '12',
            tempF: '54',
            windspeedMiles: '9',
            windspeedKmph: '14',
            winddirDegree: '67',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '37',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1026',
            pressureInches: '31',
            cloudcover: '64',
            HeatIndexC: '12',
            HeatIndexF: '54',
            DewPointC: '-2',
            DewPointF: '29',
            WindChillC: '11',
            WindChillF: '52',
            WindGustMiles: '12',
            WindGustKmph: '19',
            FeelsLikeC: '11',
            FeelsLikeF: '52',
            chanceofrain: '0',
            chanceofremdry: '89',
            chanceofwindy: '0',
            chanceofovercast: '71',
            chanceofsunshine: '34',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1700',
            tempC: '12',
            tempF: '54',
            windspeedMiles: '8',
            windspeedKmph: '13',
            winddirDegree: '68',
            winddir16Point: 'ENE',
            weatherCode: '119',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Хмарно',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '39',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1025',
            pressureInches: '31',
            cloudcover: '71',
            HeatIndexC: '12',
            HeatIndexF: '54',
            DewPointC: '-1',
            DewPointF: '30',
            WindChillC: '11',
            WindChillF: '52',
            WindGustMiles: '12',
            WindGustKmph: '19',
            FeelsLikeC: '11',
            FeelsLikeF: '52',
            chanceofrain: '0',
            chanceofremdry: '93',
            chanceofwindy: '0',
            chanceofovercast: '83',
            chanceofsunshine: '16',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1800',
            tempC: '11',
            tempF: '53',
            windspeedMiles: '8',
            windspeedKmph: '12',
            winddirDegree: '67',
            winddir16Point: 'ENE',
            weatherCode: '122',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Overcast',
              },
            ],
            lang_uk: [
              {
                value: 'Суцільна хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '43',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1025',
            pressureInches: '31',
            cloudcover: '81',
            HeatIndexC: '11',
            HeatIndexF: '53',
            DewPointC: '-1',
            DewPointF: '31',
            WindChillC: '10',
            WindChillF: '50',
            WindGustMiles: '12',
            WindGustKmph: '19',
            FeelsLikeC: '10',
            FeelsLikeF: '50',
            chanceofrain: '0',
            chanceofremdry: '92',
            chanceofwindy: '0',
            chanceofovercast: '85',
            chanceofsunshine: '17',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1900',
            tempC: '11',
            tempF: '51',
            windspeedMiles: '7',
            windspeedKmph: '12',
            winddirDegree: '66',
            winddir16Point: 'ENE',
            weatherCode: '119',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Хмарно',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '47',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1025',
            pressureInches: '31',
            cloudcover: '90',
            HeatIndexC: '11',
            HeatIndexF: '51',
            DewPointC: '-0',
            DewPointF: '31',
            WindChillC: '9',
            WindChillF: '48',
            WindGustMiles: '12',
            WindGustKmph: '19',
            FeelsLikeC: '9',
            FeelsLikeF: '48',
            chanceofrain: '0',
            chanceofremdry: '92',
            chanceofwindy: '0',
            chanceofovercast: '87',
            chanceofsunshine: '18',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '2000',
            tempC: '10',
            tempF: '50',
            windspeedMiles: '7',
            windspeedKmph: '11',
            winddirDegree: '65',
            winddir16Point: 'ENE',
            weatherCode: '122',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Overcast',
              },
            ],
            lang_uk: [
              {
                value: 'Суцільна хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '51',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1024',
            pressureInches: '31',
            cloudcover: '100',
            HeatIndexC: '10',
            HeatIndexF: '50',
            DewPointC: '0',
            DewPointF: '32',
            WindChillC: '8',
            WindChillF: '47',
            WindGustMiles: '12',
            WindGustKmph: '20',
            FeelsLikeC: '8',
            FeelsLikeF: '47',
            chanceofrain: '0',
            chanceofremdry: '91',
            chanceofwindy: '0',
            chanceofovercast: '89',
            chanceofsunshine: '19',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '2100',
            tempC: '9',
            tempF: '49',
            windspeedMiles: '7',
            windspeedKmph: '11',
            winddirDegree: '67',
            winddir16Point: 'ENE',
            weatherCode: '119',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Хмарно',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '54',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1024',
            pressureInches: '31',
            cloudcover: '94',
            HeatIndexC: '9',
            HeatIndexF: '49',
            DewPointC: '1',
            DewPointF: '33',
            WindChillC: '8',
            WindChillF: '46',
            WindGustMiles: '12',
            WindGustKmph: '19',
            FeelsLikeC: '8',
            FeelsLikeF: '46',
            chanceofrain: '0',
            chanceofremdry: '89',
            chanceofwindy: '0',
            chanceofovercast: '90',
            chanceofsunshine: '19',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '2200',
            tempC: '9',
            tempF: '48',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '69',
            winddir16Point: 'ENE',
            weatherCode: '122',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Overcast',
              },
            ],
            lang_uk: [
              {
                value: 'Суцільна хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '57',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1024',
            pressureInches: '31',
            cloudcover: '87',
            HeatIndexC: '9',
            HeatIndexF: '48',
            DewPointC: '1',
            DewPointF: '34',
            WindChillC: '7',
            WindChillF: '45',
            WindGustMiles: '11',
            WindGustKmph: '18',
            FeelsLikeC: '7',
            FeelsLikeF: '45',
            chanceofrain: '0',
            chanceofremdry: '88',
            chanceofwindy: '0',
            chanceofovercast: '91',
            chanceofsunshine: '18',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '2300',
            tempC: '9',
            tempF: '47',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '71',
            winddir16Point: 'ENE',
            weatherCode: '119',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Хмарно',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '61',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1023',
            pressureInches: '31',
            cloudcover: '81',
            HeatIndexC: '9',
            HeatIndexF: '47',
            DewPointC: '1',
            DewPointF: '34',
            WindChillC: '7',
            WindChillF: '44',
            WindGustMiles: '11',
            WindGustKmph: '18',
            FeelsLikeC: '7',
            FeelsLikeF: '44',
            chanceofrain: '0',
            chanceofremdry: '86',
            chanceofwindy: '0',
            chanceofovercast: '92',
            chanceofsunshine: '18',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
        ],
      },
      {
        date: '2020-03-28',
        astronomy: [
          {
            sunrise: '05:43 AM',
            sunset: '06:24 PM',
            moonrise: '07:36 AM',
            moonset: '10:39 PM',
            moon_phase: 'Waxing Crescent',
            moon_illumination: '25',
          },
        ],
        maxtempC: '14',
        maxtempF: '57',
        mintempC: '6',
        mintempF: '44',
        avgtempC: '10',
        avgtempF: '50',
        totalSnow_cm: '0.0',
        sunHour: '12.8',
        uvIndex: '3',
        hourly: [
          {
            time: '0',
            tempC: '8',
            tempF: '47',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '69',
            winddir16Point: 'ENE',
            weatherCode: '122',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Overcast',
              },
            ],
            lang_uk: [
              {
                value: 'Суцільна хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '62',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1023',
            pressureInches: '31',
            cloudcover: '87',
            HeatIndexC: '8',
            HeatIndexF: '47',
            DewPointC: '1',
            DewPointF: '34',
            WindChillC: '7',
            WindChillF: '44',
            WindGustMiles: '11',
            WindGustKmph: '17',
            FeelsLikeC: '7',
            FeelsLikeF: '44',
            chanceofrain: '0',
            chanceofremdry: '84',
            chanceofwindy: '0',
            chanceofovercast: '90',
            chanceofsunshine: '16',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '100',
            tempC: '8',
            tempF: '46',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '67',
            winddir16Point: 'ENE',
            weatherCode: '119',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Хмарно',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '63',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1023',
            pressureInches: '31',
            cloudcover: '94',
            HeatIndexC: '8',
            HeatIndexF: '46',
            DewPointC: '1',
            DewPointF: '34',
            WindChillC: '6',
            WindChillF: '43',
            WindGustMiles: '11',
            WindGustKmph: '17',
            FeelsLikeC: '6',
            FeelsLikeF: '43',
            chanceofrain: '0',
            chanceofremdry: '83',
            chanceofwindy: '0',
            chanceofovercast: '89',
            chanceofsunshine: '14',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '200',
            tempC: '8',
            tempF: '46',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '65',
            winddir16Point: 'ENE',
            weatherCode: '122',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Overcast',
              },
            ],
            lang_uk: [
              {
                value: 'Суцільна хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '64',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1022',
            pressureInches: '31',
            cloudcover: '100',
            HeatIndexC: '8',
            HeatIndexF: '46',
            DewPointC: '1',
            DewPointF: '34',
            WindChillC: '6',
            WindChillF: '42',
            WindGustMiles: '10',
            WindGustKmph: '17',
            FeelsLikeC: '6',
            FeelsLikeF: '42',
            chanceofrain: '0',
            chanceofremdry: '81',
            chanceofwindy: '0',
            chanceofovercast: '87',
            chanceofsunshine: '12',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '300',
            tempC: '7',
            tempF: '45',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '69',
            winddir16Point: 'ENE',
            weatherCode: '122',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Overcast',
              },
            ],
            lang_uk: [
              {
                value: 'Суцільна хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '66',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1022',
            pressureInches: '31',
            cloudcover: '99',
            HeatIndexC: '7',
            HeatIndexF: '45',
            DewPointC: '1',
            DewPointF: '34',
            WindChillC: '5',
            WindChillF: '42',
            WindGustMiles: '10',
            WindGustKmph: '17',
            FeelsLikeC: '5',
            FeelsLikeF: '42',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '86',
            chanceofsunshine: '13',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '400',
            tempC: '7',
            tempF: '44',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '72',
            winddir16Point: 'ENE',
            weatherCode: '122',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Overcast',
              },
            ],
            lang_uk: [
              {
                value: 'Суцільна хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '67',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1021',
            pressureInches: '31',
            cloudcover: '98',
            HeatIndexC: '7',
            HeatIndexF: '44',
            DewPointC: '1',
            DewPointF: '34',
            WindChillC: '5',
            WindChillF: '41',
            WindGustMiles: '11',
            WindGustKmph: '17',
            FeelsLikeC: '5',
            FeelsLikeF: '41',
            chanceofrain: '0',
            chanceofremdry: '88',
            chanceofwindy: '0',
            chanceofovercast: '84',
            chanceofsunshine: '14',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '500',
            tempC: '6',
            tempF: '44',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '76',
            winddir16Point: 'ENE',
            weatherCode: '122',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Overcast',
              },
            ],
            lang_uk: [
              {
                value: 'Суцільна хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '69',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1021',
            pressureInches: '31',
            cloudcover: '97',
            HeatIndexC: '6',
            HeatIndexF: '44',
            DewPointC: '1',
            DewPointF: '34',
            WindChillC: '4',
            WindChillF: '40',
            WindGustMiles: '11',
            WindGustKmph: '17',
            FeelsLikeC: '4',
            FeelsLikeF: '40',
            chanceofrain: '0',
            chanceofremdry: '92',
            chanceofwindy: '0',
            chanceofovercast: '83',
            chanceofsunshine: '15',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '600',
            tempC: '7',
            tempF: '44',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '76',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '69',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1020',
            pressureInches: '31',
            cloudcover: '83',
            HeatIndexC: '7',
            HeatIndexF: '44',
            DewPointC: '2',
            DewPointF: '35',
            WindChillC: '5',
            WindChillF: '40',
            WindGustMiles: '10',
            WindGustKmph: '16',
            FeelsLikeC: '5',
            FeelsLikeF: '40',
            chanceofrain: '0',
            chanceofremdry: '88',
            chanceofwindy: '0',
            chanceofovercast: '65',
            chanceofsunshine: '36',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '700',
            tempC: '7',
            tempF: '45',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '76',
            winddir16Point: 'ENE',
            weatherCode: '122',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Overcast',
              },
            ],
            lang_uk: [
              {
                value: 'Суцільна хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '69',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1020',
            pressureInches: '31',
            cloudcover: '70',
            HeatIndexC: '7',
            HeatIndexF: '45',
            DewPointC: '2',
            DewPointF: '36',
            WindChillC: '5',
            WindChillF: '41',
            WindGustMiles: '9',
            WindGustKmph: '14',
            FeelsLikeC: '5',
            FeelsLikeF: '41',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '48',
            chanceofsunshine: '57',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '800',
            tempC: '8',
            tempF: '46',
            windspeedMiles: '7',
            windspeedKmph: '11',
            winddirDegree: '77',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '70',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1019',
            pressureInches: '31',
            cloudcover: '57',
            HeatIndexC: '8',
            HeatIndexF: '46',
            DewPointC: '2',
            DewPointF: '36',
            WindChillC: '6',
            WindChillF: '42',
            WindGustMiles: '8',
            WindGustKmph: '13',
            FeelsLikeC: '6',
            FeelsLikeF: '42',
            chanceofrain: '0',
            chanceofremdry: '81',
            chanceofwindy: '0',
            chanceofovercast: '30',
            chanceofsunshine: '78',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '900',
            tempC: '9',
            tempF: '48',
            windspeedMiles: '7',
            windspeedKmph: '12',
            winddirDegree: '76',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '64',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1019',
            pressureInches: '31',
            cloudcover: '53',
            HeatIndexC: '9',
            HeatIndexF: '48',
            DewPointC: '2',
            DewPointF: '36',
            WindChillC: '7',
            WindChillF: '45',
            WindGustMiles: '9',
            WindGustKmph: '14',
            FeelsLikeC: '7',
            FeelsLikeF: '45',
            chanceofrain: '0',
            chanceofremdry: '83',
            chanceofwindy: '0',
            chanceofovercast: '33',
            chanceofsunshine: '80',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1000',
            tempC: '10',
            tempF: '50',
            windspeedMiles: '7',
            windspeedKmph: '12',
            winddirDegree: '75',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '58',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1018',
            pressureInches: '31',
            cloudcover: '50',
            HeatIndexC: '10',
            HeatIndexF: '50',
            DewPointC: '2',
            DewPointF: '35',
            WindChillC: '8',
            WindChillF: '47',
            WindGustMiles: '9',
            WindGustKmph: '14',
            FeelsLikeC: '8',
            FeelsLikeF: '47',
            chanceofrain: '0',
            chanceofremdry: '84',
            chanceofwindy: '0',
            chanceofovercast: '35',
            chanceofsunshine: '82',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1100',
            tempC: '11',
            tempF: '52',
            windspeedMiles: '8',
            windspeedKmph: '13',
            winddirDegree: '75',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '52',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1018',
            pressureInches: '31',
            cloudcover: '46',
            HeatIndexC: '11',
            HeatIndexF: '52',
            DewPointC: '2',
            DewPointF: '35',
            WindChillC: '10',
            WindChillF: '49',
            WindGustMiles: '9',
            WindGustKmph: '14',
            FeelsLikeC: '10',
            FeelsLikeF: '49',
            chanceofrain: '0',
            chanceofremdry: '86',
            chanceofwindy: '0',
            chanceofovercast: '38',
            chanceofsunshine: '84',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1200',
            tempC: '12',
            tempF: '54',
            windspeedMiles: '8',
            windspeedKmph: '13',
            winddirDegree: '76',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '47',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1017',
            pressureInches: '31',
            cloudcover: '45',
            HeatIndexC: '12',
            HeatIndexF: '54',
            DewPointC: '1',
            DewPointF: '34',
            WindChillC: '11',
            WindChillF: '51',
            WindGustMiles: '9',
            WindGustKmph: '14',
            FeelsLikeC: '11',
            FeelsLikeF: '51',
            chanceofrain: '0',
            chanceofremdry: '87',
            chanceofwindy: '0',
            chanceofovercast: '37',
            chanceofsunshine: '79',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1300',
            tempC: '13',
            tempF: '55',
            windspeedMiles: '8',
            windspeedKmph: '13',
            winddirDegree: '78',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '43',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1016',
            pressureInches: '30',
            cloudcover: '45',
            HeatIndexC: '13',
            HeatIndexF: '55',
            DewPointC: '1',
            DewPointF: '33',
            WindChillC: '12',
            WindChillF: '53',
            WindGustMiles: '9',
            WindGustKmph: '15',
            FeelsLikeC: '12',
            FeelsLikeF: '53',
            chanceofrain: '0',
            chanceofremdry: '88',
            chanceofwindy: '0',
            chanceofovercast: '36',
            chanceofsunshine: '75',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1400',
            tempC: '14',
            tempF: '57',
            windspeedMiles: '8',
            windspeedKmph: '13',
            winddirDegree: '80',
            winddir16Point: 'E',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '38',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1015',
            pressureInches: '30',
            cloudcover: '44',
            HeatIndexC: '14',
            HeatIndexF: '57',
            DewPointC: '-0',
            DewPointF: '32',
            WindChillC: '13',
            WindChillF: '55',
            WindGustMiles: '9',
            WindGustKmph: '15',
            FeelsLikeC: '13',
            FeelsLikeF: '55',
            chanceofrain: '0',
            chanceofremdry: '89',
            chanceofwindy: '0',
            chanceofovercast: '35',
            chanceofsunshine: '70',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1500',
            tempC: '14',
            tempF: '57',
            windspeedMiles: '8',
            windspeedKmph: '13',
            winddirDegree: '77',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '40',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1015',
            pressureInches: '30',
            cloudcover: '33',
            HeatIndexC: '14',
            HeatIndexF: '57',
            DewPointC: '0',
            DewPointF: '33',
            WindChillC: '13',
            WindChillF: '55',
            WindGustMiles: '9',
            WindGustKmph: '15',
            FeelsLikeC: '13',
            FeelsLikeF: '55',
            chanceofrain: '0',
            chanceofremdry: '87',
            chanceofwindy: '0',
            chanceofovercast: '37',
            chanceofsunshine: '75',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1600',
            tempC: '14',
            tempF: '57',
            windspeedMiles: '8',
            windspeedKmph: '12',
            winddirDegree: '74',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '41',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1014',
            pressureInches: '30',
            cloudcover: '22',
            HeatIndexC: '14',
            HeatIndexF: '57',
            DewPointC: '1',
            DewPointF: '33',
            WindChillC: '13',
            WindChillF: '55',
            WindGustMiles: '9',
            WindGustKmph: '15',
            FeelsLikeC: '13',
            FeelsLikeF: '55',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '40',
            chanceofsunshine: '81',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1700',
            tempC: '14',
            tempF: '56',
            windspeedMiles: '7',
            windspeedKmph: '12',
            winddirDegree: '72',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '42',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1014',
            pressureInches: '30',
            cloudcover: '11',
            HeatIndexC: '14',
            HeatIndexF: '56',
            DewPointC: '1',
            DewPointF: '34',
            WindChillC: '13',
            WindChillF: '55',
            WindGustMiles: '9',
            WindGustKmph: '15',
            FeelsLikeC: '13',
            FeelsLikeF: '55',
            chanceofrain: '0',
            chanceofremdry: '83',
            chanceofwindy: '0',
            chanceofovercast: '42',
            chanceofsunshine: '86',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1800',
            tempC: '13',
            tempF: '55',
            windspeedMiles: '6',
            windspeedKmph: '10',
            winddirDegree: '71',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '46',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1013',
            pressureInches: '30',
            cloudcover: '10',
            HeatIndexC: '13',
            HeatIndexF: '55',
            DewPointC: '1',
            DewPointF: '34',
            WindChillC: '12',
            WindChillF: '53',
            WindGustMiles: '9',
            WindGustKmph: '14',
            FeelsLikeC: '12',
            FeelsLikeF: '53',
            chanceofrain: '0',
            chanceofremdry: '85',
            chanceofwindy: '0',
            chanceofovercast: '40',
            chanceofsunshine: '84',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '3',
          },
          {
            time: '1900',
            tempC: '12',
            tempF: '53',
            windspeedMiles: '5',
            windspeedKmph: '9',
            winddirDegree: '71',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '50',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1013',
            pressureInches: '30',
            cloudcover: '10',
            HeatIndexC: '12',
            HeatIndexF: '53',
            DewPointC: '2',
            DewPointF: '35',
            WindChillC: '11',
            WindChillF: '52',
            WindGustMiles: '8',
            WindGustKmph: '13',
            FeelsLikeC: '11',
            FeelsLikeF: '52',
            chanceofrain: '0',
            chanceofremdry: '86',
            chanceofwindy: '0',
            chanceofovercast: '37',
            chanceofsunshine: '82',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '2000',
            tempC: '11',
            tempF: '52',
            windspeedMiles: '4',
            windspeedKmph: '7',
            winddirDegree: '70',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '54',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1013',
            pressureInches: '30',
            cloudcover: '9',
            HeatIndexC: '11',
            HeatIndexF: '52',
            DewPointC: '2',
            DewPointF: '36',
            WindChillC: '10',
            WindChillF: '51',
            WindGustMiles: '7',
            WindGustKmph: '12',
            FeelsLikeC: '10',
            FeelsLikeF: '51',
            chanceofrain: '0',
            chanceofremdry: '88',
            chanceofwindy: '0',
            chanceofovercast: '35',
            chanceofsunshine: '80',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '2100',
            tempC: '11',
            tempF: '51',
            windspeedMiles: '4',
            windspeedKmph: '6',
            winddirDegree: '78',
            winddir16Point: 'ENE',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '55',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1013',
            pressureInches: '30',
            cloudcover: '9',
            HeatIndexC: '11',
            HeatIndexF: '51',
            DewPointC: '2',
            DewPointF: '36',
            WindChillC: '10',
            WindChillF: '50',
            WindGustMiles: '6',
            WindGustKmph: '10',
            FeelsLikeC: '10',
            FeelsLikeF: '50',
            chanceofrain: '0',
            chanceofremdry: '87',
            chanceofwindy: '0',
            chanceofovercast: '36',
            chanceofsunshine: '83',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '2200',
            tempC: '10',
            tempF: '51',
            windspeedMiles: '3',
            windspeedKmph: '5',
            winddirDegree: '85',
            winddir16Point: 'E',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '57',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1012',
            pressureInches: '30',
            cloudcover: '9',
            HeatIndexC: '10',
            HeatIndexF: '51',
            DewPointC: '2',
            DewPointF: '36',
            WindChillC: '10',
            WindChillF: '50',
            WindGustMiles: '5',
            WindGustKmph: '8',
            FeelsLikeC: '10',
            FeelsLikeF: '50',
            chanceofrain: '0',
            chanceofremdry: '87',
            chanceofwindy: '0',
            chanceofovercast: '36',
            chanceofsunshine: '85',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
          {
            time: '2300',
            tempC: '10',
            tempF: '50',
            windspeedMiles: '2',
            windspeedKmph: '4',
            winddirDegree: '93',
            winddir16Point: 'E',
            weatherCode: '116',
            weatherIconUrl: [
              {
                value:
                  'http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png',
              },
            ],
            weatherDesc: [
              {
                value: 'Partly cloudy',
              },
            ],
            lang_uk: [
              {
                value: 'Невелика хмарність',
              },
            ],
            precipMM: '0.0',
            precipInches: '0.0',
            humidity: '58',
            visibility: '10',
            visibilityMiles: '6',
            pressure: '1012',
            pressureInches: '30',
            cloudcover: '8',
            HeatIndexC: '10',
            HeatIndexF: '50',
            DewPointC: '2',
            DewPointF: '36',
            WindChillC: '10',
            WindChillF: '50',
            WindGustMiles: '4',
            WindGustKmph: '6',
            FeelsLikeC: '10',
            FeelsLikeF: '50',
            chanceofrain: '0',
            chanceofremdry: '86',
            chanceofwindy: '0',
            chanceofovercast: '37',
            chanceofsunshine: '88',
            chanceoffrost: '0',
            chanceofhightemp: '0',
            chanceoffog: '0',
            chanceofsnow: '0',
            chanceofthunder: '0',
            uvIndex: '1',
          },
        ],
      },
    ],
  },
};

function parseWeatherData(data) {
  const weatherData = data.data.weather;
  const weather = [];
  const timeStep = [
    '200',
    '500',
    '800',
    '1100',
    '1400',
    '1700',
    '2000',
    '2300',
  ];

  // request
  const request = data.data.request[0].query;

  weather.timeZone = cutTimeZone(request);

  // currentWheather
  const currentWeather = {};
  const currentWheatherData = data.data.current_condition[0];
  currentWeather.tempC = Number(currentWheatherData.temp_C);
  currentWeather.desrEn = currentWheatherData.weatherDesc[0].value;
  currentWeather.desrUk = currentWheatherData.lang_uk[0].value;
  currentWeather.windSpeed = windSpeedRound(currentWheatherData.windspeedKmph);
  currentWeather.windFrom = currentWheatherData.winddir16Point;
  currentWeather.humidity = currentWheatherData.humidity;
  currentWeather.pressure = convertPressure(currentWheatherData.pressure);

  weather.currentWeather = currentWeather;

  // weatherData
  const days = [];
  weatherData.map(el => {
    const hourly = [];
    const daysTmp = {};
    daysTmp.timeDate = el.date;
    daysTmp.sunRise = el.astronomy[0].sunrise;
    daysTmp.sunSet = el.astronomy[0].sunset;
    daysTmp.maxTemp = el.maxtempC;
    daysTmp.minTemp = el.mintempC;
    daysTmp.sunTotalHours = el.sunHour;

    // фільтруєм тільки потрібні години 2, 5, 8, 11, 14, 17, 20, 23
    el.hourly.map(h => {
      timeStep.map(t => {
        if (h.time === t) {
          const hourlyTmp = {};

          hourlyTmp.time = Number(h.time.substr(0, h.time.length - 2));

          hourlyTmp.tempС = Number(h.tempC);

          hourlyTmp.tempFeelsLikeС = Number(h.FeelsLikeC);

          hourlyTmp.windSpeed = windSpeedRound(h.windspeedKmph);

          hourlyTmp.windFrom = h.winddir16Point;

          hourlyTmp.desrEn = h.weatherDesc[0].value;

          hourlyTmp.desrUk = h.lang_uk[0].value;

          hourlyTmp.humidity = Number(h.humidity);

          hourlyTmp.pressure = convertPressure(h.pressure);

          hourlyTmp.chanceOfRain = h.chanceofrain;

          hourly.push(hourlyTmp);
        }
      });
      daysTmp.hourly = hourly;
    });
    days.push(daysTmp);
  });

  weather.days = days;

  return weather;
}

parseWeatherData(data);
// 000 time перевести UNIX час в години
function cutTimeZone(timezone) {
  const index = timezone.indexOf(',');
  const cutString = timezone.slice(0, index);
  return cutString;
}

//  time перевести UNIX час в години
// function convertTime(unixTime) {
//   const t = new Date(unixTime * 1000);
//   //   const months = [
//   //     'Січень',
//   //     'Лютий',
//   //     'Березень',
//   //     'Квітень',
//   //     'Травень',
//   //     'Червень',
//   //     'Липень',
//   //     'Серпень',
//   //     'Вересень',
//   //     'Жовтень',
//   //     'Листопад',
//   //     'Грудень',
//   //   ];
//   //   const year = t.getFullYear();
//   //   const month = months[t.getMonth()];
//   //   const date = t.getDate();
//   const hour = t.getHours();
//   const min = pad(t.getMinutes());
//   //   const sec = t.getSeconds();
//   const time = `${hour} :${min}`;
//   return time;
// }

// icon знайти іконку для погоди
function findIcon(icon) {
  console.log(icon, 'icon');
}
// 000 windSpeed
function windSpeedRound(windSpeed) {
  return Math.round(((windSpeed * 1000) / 3600) * 10) / 10;
}

// 000 temperature округлити температуру
function cutTemperature(temp) {
  return Math.round(temp);
}

// 000 перевести тиск в міліметри ртутного стовпчика (* 0.7501)
function convertPressure(pressure) {
  return Math.round(pressure * 0.736);
}

// function pad(value) {
//   return String(value).padStart(2, '0');
// }
